### ISSUE TITLE
TODO new version

### ISSUE THREAD

**Issue by floriancargoet** [floriancargoet/fifty-editor#2]
### v1
- [x] save feedback
- [ ] integrate old editor
- [x] buttons style
- [x] don't lose changes when navigating (mark unsaved files? prevent navigation?)
### v1.1 (minor improvements)
- [ ] reset.css instead of bootstrap (normalize?)
- [ ] nicer local storage IDs (and/or local names)
- [ ] icons (local, dropbox, login, save)
- [ ] sort files
### v2
- [ ] alternative to oauth popup (iframe?)
- File browser
  - [ ] new files
  - [ ] folders
  - [ ] rename files
  - [ ] names for local files
  - [ ] link to dropbox files URL (https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link)
- Editor
  - [ ] autosave
  - [ ] change word target
  - [ ] goal progress bar
  - [ ] goal success animation
### vX
- [ ] google drive ?
- [ ] better prose editor (prosemirror? inspiration: http://www.hemingwayapp.com/)
